### ISSUE TITLE
issues on sending message through API

### ISSUE THREAD

**Issue by ElioErrico** [green-api/whatsapp-api-client-python#32]
I'm having problems on using this simple example:
[https://github.com/green-api/whatsapp-api-client-python/blob/master/examples/sendTextMessage.py](url)

This is what I've done:

- created a developer account on green api
- created an instance
- activated the instance through quare code
- installed libreries on my venv
- changed the code of the ,py file as following: 

> `greenAPI = API.GreenApi("IdInstance", "ApiTokenInstance")`

- changed the phone number as following:

> `response = greenAPI.sending.sendMessage("phone_number_inserted@c.us", "my_message")`

-  I tryed the following 3 phone number:

> 1. 392xxxxxx26 (without prefix)
> 2. 0039392xxxxxx26 (0039 prefix)
> 3. +39392xxxxxx26 (+39 prefix)

This is the respective output.
1. It send my message to +39 2xxxxxx26
2. it returns me this error 
> `"message": "Validation failed. Details: 'chatId' must be one of the next formats: 'phone_number@c.us' or 'group_id@g.us'"`
3.  it returns me this error
> `"message":` "Validation failed. Details: 'chatId' must be one of the next formats: 'phone_number@c.us' or 'group_id@g.us'"`

it should send it to:
+39392xxxxxx26

let me know

**Comment by kocherovv** [comment]
Hello!

At the bottom of the page you can find examples of queries in different languages.
https://green-api.com/docs/api/sending/SendMessage/ 

The chat ID has the prefix @c.us and is a string of the form 00000000000-XXXXXXXXXX@c.us or XXXXXXXXXXXXXXXXX@c.us
It should be noted that the group chat ID has the prefix @g.us and is a string of the form 00000000000-XXXXXXXXXX@g.us or XXXXXXXXXXXXXXXXX@g.us

Your number "+39392xxxxxx26" is chatId "39392xxxxxx26@c.us". 

Please read this, if you want to send messages to numbers from different countries: 
[features-of-sending-and-receiving-messages-from-different-countries](https://greenapi.com/en/docs/faq/features-of-sending-and-receiving-messages-from-different-countries/)
