### ISSUE TITLE
How to download destructive images/videos

### ISSUE THREAD

**Issue by soheru** [green-api/whatsapp-api-client-python#33]
?

**Comment by ArtyomKovl** [comment]
Please, clarify what you mean?

**Comment by soheru** [comment]
Like in WhatsApp we send photos and videos as one time view ? , So How to download those using api. Any examples?

**Comment by ArtyomKovl** [comment]
If I understand you correctly, you are interested in sending one-time messages using the API. Unfortunately, we do not have this function; this task has already been registered and transferred to the developers: https://github.com/green-api/issues/issues/250

**Comment by soheru** [comment]
i am interested in saving those messages,

for e.g you and i are talking on WhatsApp, you sent me one time message (photo) so using api , i want to save them

**Comment by ArtyomKovl** [comment]
Perhaps I didn't understand you correctly. Try using the DownloadFile method to download files: https://green-api.com/en/docs/api/receiving/files/DownloadFile/
