### ISSUE TITLE
Установка пакета происходит некорректно

### ISSUE THREAD

**Issue by Amele9** [green-api/whatsapp-api-client-python#4]
![image](https://user-images.githubusercontent.com/105914205/203922887-573a5379-0d73-4101-a448-1ab93b034f74.png)
Установил пакет с помощью команды pip install whatsapp-api-client-python. После установки заметил, что отсутствуют некоторые пакеты.

**Comment by ripreal** [comment]
Опубликовал 0.0.27, в которой откатил все до 0.0.23. Рекомендую разобраться почему собранная либа не работает на 0.0.26

**Comment by Amele9** [comment]
> Опубликовал 0.0.27, в которой откатил все до 0.0.23. Рекомендую разобраться почему собранная либа не работает на 0.0.26

![image](https://user-images.githubusercontent.com/105914205/203965047-01963738-c9b0-4486-b714-5e9c4856e6d4.png)
Она не работает и на 0.0.23.

**Comment by ripreal** [comment]
@Amele9 Возможно остались старые зависимости. Попробуйте с нуля проект сделать используя виртуальное окружение. КОгда я делаю с нуля, то на версии 0.0.27 (она же 0.0.23) работает

![image](https://user-images.githubusercontent.com/25801912/204248071-5e7dda91-01de-4b09-9497-db59f33f439b.png)

Когда я делаю на 0.0.26 с нуля проект, то он не работает

![image](https://user-images.githubusercontent.com/25801912/204249409-a54bd721-6350-404e-a4d6-9cd273063c5d.png)


Я к сожалению не сильный спец по питону и поэтому не могу чем-нибудь помочь конкретным, кроме того как протестировать. Возможно делоо в используемой IDE. Я использую блокнот, который не добавляет ничего от себя кроме как venv

**Comment by Amele9** [comment]
> @Amele9 Возможно остались старые зависимости. Попробуйте с нуля проект сделать используя виртуальное окружение. КОгда я делаю с нуля, то на версии 0.0.27 (она же 0.0.23) работает
> 
> ![image](https://user-images.githubusercontent.com/25801912/204248071-5e7dda91-01de-4b09-9497-db59f33f439b.png)
> 
> Когда я делаю на 0.0.26 с нуля проект, то он не работает
> 
> ![image](https://user-images.githubusercontent.com/25801912/204249409-a54bd721-6350-404e-a4d6-9cd273063c5d.png)
> 
> Я к сожалению не сильный спец по питону и поэтому не могу чем-нибудь помочь конкретным, кроме того как протестировать. Возможно делоо в используемой IDE. Я использую блокнот, который не добавляет ничего от себя кроме как venv

А можете показать внутренности whatsapp-api-client-python? Я установил whatsapp-api-client-python версии 0.0.26 внутри venv. Отсутствуют некоторые директории, которые были добавлены в версии 0.0.26.

Пакет не работает, потому что у вас отсутствуют некоторые директории. Я не знаю у кого ошибка, но при выполнении команды pip install whatsapp-api-client-python==0.0.26 пакет был установлен не полностью. 

Так выглядит пакет, если устанавливать через pip
![image](https://user-images.githubusercontent.com/105914205/204722722-e83ef696-cd30-4c19-ac02-dc011018e408.png)

Примерно так должен выглядеть пакет.
![image](https://user-images.githubusercontent.com/105914205/204723770-4ac94d7b-20f6-492b-aec1-5065a7cd67a9.png)

**Comment by ripreal** [comment]
@Amele9 Можно самостоятельно проверить как выглядит скомпилированная либа, скачанного в пакетном менеджере pip install -Iv whatsapp-api-client-python==0.0.26

![image](https://user-images.githubusercontent.com/25801912/204727978-404c4dd7-2b89-4bf6-8a1e-f2ecd4b6d2ea.png)

Нужно добавить в пулл-реквест необходимые изменения в файл setup.py в части модуля
