### ISSUE TITLE
add member to group issues

### ISSUE THREAD

**Issue by Alias4D** [green-api/whatsapp-api-client-python#43]
can't add members not registered on what's app phone to group ?
after run code below only numbers registered on phone added successfully 
`
tdf = pd.read_excel('Book.xlsx')
phones = tdf.Phones.tolist()
for c in phones:
    c = '964'+str(c)+'@c.us'
    print('Start Processing : '+c)
    r = wclient.groups.addGroupParticipant(group_id,c)
    time.sleep(2)
    if r.data['addParticipant']:
        print('Phone added successfully ✅')
        s.append(c)
    else:
        print('Phone added Failed ❌')
        f.append(c)
`

**Comment by ArtyomKovl** [comment]
If I understand correctly, you are unable to add members to a group if they are not in contacts?
In the web version of WhatsApp, you cannot add members to a group if they are not in contacts; our Api imitates the work of the web version. To add members to a group, add them to your contacts or send them a link to join the group.

**Comment by Alias4D** [comment]
Thanks 🙏
