### ISSUE TITLE
Question | Add member to contacts list using the API

### ISSUE THREAD

**Issue by taaaal** [green-api/whatsapp-api-client-python#45]
I have already read in a previous issue ([Issue #43](https://github.com/green-api/whatsapp-api-client-python/issues/43)) that you cannot add members to groups if they are not in your contacts. Hence my question, is it possible through the API to add members to your contacts?

_Looking forward to your reply, thanks_

**Comment by kocherovv** [comment]
> I have already read in a previous issue ([Issue #43](https://github.com/green-api/whatsapp-api-client-python/issues/43)) that you cannot add members to groups if they are not in your contacts. Hence my question, is it possible through the API to add members to your contacts?
> 
> _Looking forward to your reply, thanks_

Hello, unfortunately our API does not have a method that would add a number to contacts on your phone, since this requires access to a smartphone.
Try using third-party services and applications on your phone for this.

**Comment by EscHelpNew** [comment]
Hello, unfortunately we cannot do more than what the web version of WhatsApp allows. Adding to contacts via the web version is not possible.

**Comment by AknurKh** [comment]
@taaaal Also, we don't know services/api which supports services like contacts modification
