### ISSUE TITLE
Question | Find group's id by group name

### ISSUE THREAD

**Issue by taaaal** [green-api/whatsapp-api-client-python#47]
I did a pretty thorough search on the API docs, but maybe I missed something. 
I wanted to know if there is a way to return all the groups I am in? (to work with a specific group that I want, but I don't have its ID)

_Anyway, looking forward to any reply(:_

**Comment by ArtyomKovl** [comment]
> I did a pretty thorough search on the API docs, but maybe I missed something. I wanted to know if there is a way to return all the groups I am in? (to work with a specific group that I want, but I don't have its ID)
> 
> _Anyway, looking forward to any reply(:_

You can get the group ID using the GetContacts method: https://greenapi.com/en/docs/api/service/GetContacts/
In the article you will find ways to determine the group ID: https://greenapi.com/en/docs/api/chat-id/#gus

**Comment by taaaal** [comment]
Oh, I see. I would recommend creating something like `GreenAPI.serviceMethods.getGroups` (split the whole contacts data between `x.type == 'user'` and `x.type == 'group'`).

_Anyways, thank you(:_

**Comment by ArtyomKovl** [comment]
> Oh, I see. I would recommend creating something like `GreenAPI.serviceMethods.getGroups` (split the whole contacts data between `x.type == 'user'` and `x.type == 'group'`).
> 
> _Anyways, thank you(:_

Previously, a task was registered to improve the getContacts method to obtain a list of groups: https://github.com/green-api/issues/issues/298. The task will be completed in future releases.
