### ISSUE TITLE
Does not find the module

### ISSUE THREAD

**Issue by surgutandrey** [green-api/whatsapp-api-client-python#59]
{
	"name": "ModuleNotFoundError",
	"message": "No module named 'whatsapp_api_client_python'",
	"stack": "---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from whatsapp_api_client_python import API
      2 from datetime import datetime, timedelta
      3 from telegram import Bot

ModuleNotFoundError: No module named 'whatsapp_api_client_python'"
}

**Comment by surgutandrey** [comment]
using any virtual environment "venv" and Jupyter notebook

**Comment by astashenkoj** [comment]
In a virtual environment like Jupiter, install the module only with ! at first:
**!pip install whatsapp-api-client-python**

**Comment by surgutandrey** [comment]
I did the installation using the command:
python -m pip install whatsapp-api-client-python

The following command fails:
!pip install whatsapp-api-client-python

I use the Windows IDE: vs_code. Environment: venv and Jupiter notebook

When entering the "pip list" command, it shows:
whatsapp-api-client-python 0.0.46

and in the import team
from whatsapp_api_client_python import API

Note that in one case the underscores are lower and in the other they are not.

**Comment by AnnaVas1leva** [comment]
We tested the installation on our devices, but we were unable to reproduce your error even when using venv.
Please make sure you only have one version of Python installed on your device, this can also cause the problem with installation
