### ISSUE TITLE
Not Receiving Messages

### ISSUE THREAD

**Issue by IQExotic** [green-api/whatsapp-api-client-python#62]
Hey, I am having troubles receiving messages. On the Website on https://console.green-api.com/app/api/receiveIncomingNotifications I  only get a bunch of "null" and in my code I get nothing and after a while I get internal server error Code 500.
I have tried multiple ways even with your handler. my last version was:
```
def onEvent(typeWebhook, body):
    print("Received notification:")
    print("Type:", typeWebhook)
    print("Body:", body)

greenAPI.webhooks.startReceivingNotifications(onEvent)
```
I would really be happy if you could give me a quick response ;)

**Comment by Viacheslav-green-api** [comment]
Good evening!

Make sure you have enabled incoming webhooks in your settings. Read our article https://greenapi.com/en/docs/api/recommendations/working-with-incomming-webhooks/#001

**Comment by Viacheslav-green-api** [comment]
Receive webhooks via HTTP API[#](https://greenapi.com/en/docs/api/receiving/technology-http-api/#receive-webhooks-via-http-api)
You can get incoming webhooks (messages, statuses) via HTTP API requests in the similar way as the rest of the Green API methods are implemented. Herewith, the chronological order of the webhooks following is guaranteed in the sequence in which they were received [FIFO](https://ru.wikipedia.org/wiki/FIFO). All incoming webhooks are stored in the queue and are expected to be received within 24 hours.

To get incoming webhooks, you have to sequentially call two methods [ReceiveNotification](https://greenapi.com/en/docs/api/receiving/technology-http-api/ReceiveNotification/) and [DeleteNotification](https://greenapi.com/en/docs/api/receiving/technology-http-api/DeleteNotification/). [ReceiveNotification](https://greenapi.com/en/docs/api/receiving/technology-http-api/ReceiveNotification/) method receives an incoming webhook. [DeleteNotification](https://greenapi.com/en/docs/api/receiving/technology-http-api/DeleteNotification/) method confirms successful webhook receipt and processing. To learn more about the methods, refer to respective [ReceiveNotification](https://greenapi.com/en/docs/api/receiving/technology-http-api/ReceiveNotification/) and [DeleteNotification](https://greenapi.com/en/docs/api/receiving/technology-http-api/DeleteNotification/) sections.

Incoming webhooks are stored for 24 hours. https://greenapi.com/en/docs/api/receiving/technology-http-api/

**Comment by IQExotic** [comment]
Hey, Thanks!
I already figured that out.
It works now. Do you know who I have to talk to for custom Comercial solutions? We would need it for our internal system in terms of Pricing?
Thanks again for the Help!

**Comment by Viacheslav-green-api** [comment]
Hello!

To agree on partnership terms, we need additional information:

1. What service do you have (link to website and description of the service)?

2. Planned use case for the WhatsApp channel?

3. What is the approximate number of instances you plan to connect (now and in the future)?

4. How did you find out about our service? 

5. Within which country do you operate and organize your activities?

6. Please specify your current contact number for operational communication.

Thanks for the answers!

**Comment by IQExotic** [comment]
Thanks for the fast response!
Is there a Contact E-Mail or anything. Since I don't want to
Share sensitive information like this in the Public!

**Comment by AknurKh** [comment]
@IQExotic You can send answers to our WhatsApp, Telegram or email. Here contacts:
- WhatsApp: [+7 727 312 2366](https://wa.me/77273122366)
- [Telegram](https://t.me/greenapi_support_eng_bot)
- Email: support@greenapi.com
