### ISSUE TITLE
Asking for a rework to ReadME

### ISSUE THREAD

**Issue by CorruptedSpring** [green-api/whatsapp-api-client-python#66]
ReadME need to be worked on
For example when initiating an object 
greenAPI = API.GreenAPI(
    "1101000001", "d75b3a66374942c5b3c019c698abc2067e151558acbd412345"
)
what do you mean by "1101000001" or "d75b3a66374942c5b3c019c698abc2067e151558acbd412345"?
More documentation would help a lot thank you

**Comment by astashenkoj** [comment]
@CorruptedSpring  Hello! 1101000001 refers to your instance number (idInstance), d75b3a66374942c5b3c019c698abc2067e151558acbd412345 refers to the instance token (apiTokenInstance).

To execute HTTP API WhatsApp requests, you need to use the access parameters to instance. Access parameters are published in [console](https://console.green-api.com/):

`apiUrl` - API host link
`mediaUrl` - API host link for sending files
`idInstance` - instance unique number
`apiTokenInstance` - instance access key

We recommend that you read the articles on our website "[Before you start](https://green-api.com/en/docs/before-start/)"  and "[Execute requests](https://green-api.com/en/docs/request-format/)".

Also at the beginning of the [ReadME](https://github.com/green-api/whatsapp-api-client-python/blob/master/README.md) file there are links to our documentation.
